const express = require('express')
const router = express.Router()
const controller = require('../app/Http/Controllers/Controller')
const {Default} = require('./route')

router.get(Default.feature.Master.master_group, controller.MasterController.getGroup)
router.get(Default.feature.Master.master_gender, controller.MasterController.getGender)
router.get(Default.feature.Master.master_entity, controller.MasterController.getEntity)
router.get(Default.feature.Master.master_bp_type, controller.MasterController.getBpType)
router.get(Default.feature.Master.master_citizen, controller.MasterController.getCitizen)
router.get(Default.feature.Master.master_periode, controller.MasterController.getPeriode)
router.get(Default.feature.Master.master_currency, controller.MasterController.getCurrency)
router.get(Default.feature.Master.master_location, controller.MasterController.getLocation)
router.get(Default.feature.Master.master_addr_type, controller.MasterController.getAddrType)
router.get(Default.feature.Master.master_blood_group, controller.MasterController.getBloodGroup)
router.get(Default.feature.Master.master_tax_invoice, controller.MasterController.getTaxInvoice)
router.get(Default.feature.Master.master_payment_type, controller.MasterController.getPaymentType)
router.get(Default.feature.Master.master_sales_program, controller.MasterController.getSalesProgram)
router.get(Default.feature.Master.master_payment_method, controller.MasterController.getPaymentMethod)
router.get(Default.feature.Master.master_contact_person, controller.MasterController.getContactPerson)
router.get(Default.feature.Master.master_credit_terms, controller.MasterController.getCreditTermsMstr)
router.get(Default.feature.Master.master_default_periode, controller.MasterController.getDefaultPeriode)

module.exports = router